### ISSUE TITLE
how to log return?

### ISSUE THREAD

**Issue by mrchypark** [gofiber/logger#10]
I find out request body option. (Thank you!)

But how to log return?
I tried to `string(c.Fasthttp.Response.Body())` but crash text print out.

**Comment by Fenny** [comment]
Hi @mrchypark, we currently do not support logging the response body. But we might add a function to create custom logger tags.

Could you show us the error?

**Comment by mrchypark** [comment]
https://github.com/mrchypark/logger/blob/v0.2.4/main.go

line 144.

It's not return error, just return some text like below:
```
�       n��t�1K1����s�j[�,N���E����P�%G�E(G���"8(EW]�.��L~�\�pr�x����'E��
k��/��ց��'����h�0w��%p4˅���0�I���ͯۃt��O7��%���ڻ��xVl�Ԧ��ɬ��������ZmVNu���
                                                                        E��c�`X��2���s�x�P�͵��s,���y�ѫ
```

**Comment by Fenny** [comment]
That looks like compressed body data, the logger does not uncompress automatically, this would cause CPU overhead.

**Comment by mrchypark** [comment]
oh, thank you. i understand.
