### ISSUE TITLE
[REQ] - Include error in logs?

### ISSUE THREAD

**Issue by mewben** [gofiber/logger#2]
Hi, any chance to include error in logs? Like the one implemented here? https://github.com/labstack/echo/blob/master/middleware/logger.go

**Comment by Fenny** [comment]
@mewben it's possible to add an error value by checking if [c.Error()](https://docs.gofiber.io/context#error) is not `nil` after calling c.Next().

I'm currently working on other middlewares, could you create an PR?

**Comment by Fenny** [comment]
`error` is now supported in `v0.0.6` https://github.com/gofiber/logger/releases/tag/v0.0.6
